openapi: 3.0.0
info:
  title: Rain Today API
  version: 1.0.0
servers:
- url: /rain-api
paths:
  /wet-today:
    get:
      summary: Returns all records from the wet_today table.
      operationId: controller_get_wet_today
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WetToday"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /wet-today/{date}:
    get:
      summary: Returns wet_today records for the specified date.
      operationId: controller_get_wet_today_by_date
      parameters:
      - name: date
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: date
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WetToday"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /wet-kb:
    get:
      summary: Returns all records from the wet_kb table.
      operationId: controller_get_wet_kb
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WetKB"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /wet-kb/{date}:
    get:
      summary: Returns wet_kb records for the specified date.
      operationId: controller_get_wet_kb_by_date
      parameters:
      - name: date
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: date
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WetKB"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    WetToday:
      type: object
      properties:
        id:
          type: integer
        temperature:
          type: number
          format: float
        humidity:
          type: number
          format: float
        rainfall:
          type: number
          format: float
        rainfall24hr:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time
      example:
        rainfall: 5.962134
        temperature: 6.0274563
        rainfall24hr: 5.637377
        humidity: 1.4658129
        id: 0
        timestamp: 2000-01-23T04:56:07.000+00:00
    WetKB:
      type: object
      properties:
        id:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        temperature:
          type: number
          format: float
        humidity:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time
      example:
        latitude: 6.0274563
        temperature: 5.962134
        humidity: 5.637377
        id: 0
        longitude: 1.4658129
        timestamp: 2000-01-23T04:56:07.000+00:00

