import sys
import os
from flask_cors import CORS  # Import CORS for handling cross-origin requests
from controller import get_weather_from_openweathermap


if not os.path.exists("config.py"):
    print("Configuration 'config.py' not found.  "
          "You may create one from 'config.py.example'.")
    sys.exit(1)

from config import OPENAPI_STUB_DIR

if not os.path.exists(OPENAPI_STUB_DIR):
    print(f"Folder '{OPENAPI_STUB_DIR}' not found.  "
          "Please create the folder and extract zip file "
          "generated by openapi-generator into it.")
    sys.exit(1)

sys.path.append(OPENAPI_STUB_DIR)

try:
    import connexion  # Connexion is a library for creating REST APIs
except ModuleNotFoundError:
    print("Please install all required packages by running:"
          " pip install -r requirements.txt")
    sys.exit(1)

from swagger_server import encoder
def main():
    app = connexion.App(__name__, specification_dir='./')
    CORS(app.app)  # My Frontend and Backend are on different ports, so I need to enable CORS
    app.app.json_encoder = encoder.JSONEncoder
    app.add_api('rain-today.yaml',
                arguments={'title': 'Rain Today API'},
                pythonic_params=True)

    # Add the weather endpoint
    app.app.add_url_rule('/api/weather', 'get_weather_from_openweathermap', get_weather_from_openweathermap, methods=['GET'])

    app.run(port=8080, debug=True)

if __name__ == '__main__':
    main()