openapi: 3.0.0
info:
  title: Rain Today API
  version: 1.0.0
servers:
- url: /rain-api
paths:
  /wet-today:
    get:
      summary: Returns all records from the wet_today table.
      operationId: controller.get_wet_today
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WetToday'
  /wet-today/{date}:
    parameters:
    - name: date
      in: path
      required: true
      schema:
        type: string
        format: date
    get:
      summary: Returns wet_today records for the specified date.
      operationId: controller.get_wet_today_by_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WetToday'
  /wet-kb:
    get:
      summary: Returns all records from the wet_kb table.
      operationId: controller.get_wet_kb
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WetKB'
  /wet-kb/{date}:
    parameters:
    - name: date
      in: path
      required: true
      schema:
        type: string
        format: date
    get:
      summary: Returns wet_kb records for the specified date.
      operationId: controller.get_wet_kb_by_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WetKB'

components:
  schemas:
    WetToday:
      type: object
      properties:
        id:
          type: integer
        temperature:
          type: number
          format: float
        humidity:
          type: number
          format: float
        rainfall:
          type: number
          format: float
        rainfall24hr:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time
    WetKB:
      type: object
      properties:
        id:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        temperature:
          type: number
          format: float
        humidity:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time